---
title: "MI Paper Tables"
author: "Kylie Getz and Kristin Linn"
date: "6/28/2022"
output: pdf_document
---

Results using 1000 simulations, 10 MI
trueTreatment approx -0.69, trueEcog appox 0.4

os1 <- coxph(Surv(cmonth, dead) ~ treat + genderf +  
reth_black + reth_hisp + reth_oth + practypec + b.ecogvalue + smokey +  dgradeh + surgery + site_ureter + site_renal + site_urethra + age + var1 + var2, data=sdat.c, x=T)

# Full Model Results 
```{r echo=F, include=F}
library(ggplot2)
library(gridExtra)
library(grid)
library(xtable)
library(kableExtra)
library(dplyr)
library(reshape2)

rootdir = "~/Box Sync/Mentoring/Students/Getz_Kylie/results"
fdir = file.path (rootdir, "2022_06_28/final_results")

getDfs <- function (mdm, pc){
  # Oracle, CC, MICE, and RF
  avgName = paste0 ("Avgs_", mdm, "_", pc, ".csv")
  avgDf = read.csv (file.path (fdir, avgName))
  # AE
  avgName = paste0 ("AE", avgName)  
  aeAvg =  read.csv (file.path (fdir, avgName))
  colnames (aeAvg) = c ("X", "biasAE", "seAE", "coverageAE", "mseAE")
  aeAvg$X = avgDf$X
  avgDf = left_join (avgDf, aeAvg, by='X')
  avgDf$percMiss = pc
  return (avgDf)
}

MCAR10 = getDfs ('MCAR', 10)
MCAR30 = getDfs ('MCAR', 30)
MCAR50 = getDfs ('MCAR', 50)
MCAR = rbind (MCAR10, MCAR30, MCAR50)
MCAR$type = 'MCAR'

MAR10 = getDfs ('MAR', 10)
MAR30 = getDfs ('MAR', 30)
MAR50 = getDfs ('MAR', 50)
MAR = rbind (MAR10, MAR30, MAR50)
MAR$type = 'MAR'

MNAR10a = getDfs ('MNAR1', 10)
MNAR30a = getDfs ('MNAR1', 30)
MNAR50a = getDfs ('MNAR1', 50)
MNAR1 = rbind (MNAR10a, MNAR30a, MNAR50a)
MNAR1$type = 'MNAR1'

MNAR10b = getDfs ('MNAR2', 10)
MNAR30b = getDfs ('MNAR2', 30)
MNAR50b = getDfs ('MNAR2', 50)
MNAR2 = rbind (MNAR10b, MNAR30b, MNAR50b)
MNAR2$type = 'MNAR2'

allData = rbind (MCAR, MAR, MNAR1, MNAR2)
```


```{r echo=F, include=F}
TreatInds = which (allData$X=='treat')
EcogInds = which (allData$X=='b.ecogvalue')
Var1Inds = which (allData$X=='var1')
Var2Inds = which (allData$X=='var2')

biasCols = c (2:5, 18, 23)
seCols = c (6:9, 19, 23)
coverageCols = c (10:13, 20, 23)
mseCols = c (14:17, 21, 23)

```

```{r echo=F, include=F}
prop <- c(10,30,50,10,30,50,10,30,50)

# Table 1: Treat Bias and MSE
getRows = allData[TreatInds,]

# MCAR
tab1MCARbias = filter (getRows[,biasCols], type=='MCAR')
tab1MCARbias$type = NULL

# MAR
tab1MARbias = filter (getRows[,biasCols], type=='MAR')
tab1MARbias$type = NULL

# MNAR1
tab1MNAR1bias = filter (getRows[,biasCols], type=='MNAR1')
tab1MNAR1bias$type = NULL

# MNAR2
tab1MNAR2bias = filter (getRows[,biasCols], type=='MNAR2')
tab1MNAR2bias$type = NULL

# Table 2: Treat SE and coverage

# MCAR
tab2MCARse = filter (getRows[,seCols], type=='MCAR')
tab2MCARcoverage = filter (getRows[,coverageCols], type=='MCAR')
tab2MCARse$type = NULL
tab2MCARcoverage$type = NULL

tab2MCAR <- cbind(t (tab1MCARbias), t (tab2MCARse), t (tab2MCARcoverage))
tab2MCAR <- rbind(prop,tab2MCAR)
rownames(tab2MCAR) <- c("prop","ORACLE", "CC", "MICE", "RF", "DAE")

# MAR
tab2MARse = filter (getRows[,seCols], type=='MAR')
tab2MARcoverage = filter (getRows[,coverageCols], type=='MAR')
tab2MARse$type = NULL
tab2MARcoverage$type = NULL

tab2MAR <- cbind(t (tab1MARbias), t (tab2MARse), t (tab2MARcoverage))
tab2MAR <- rbind(prop,tab2MAR)
rownames(tab2MAR) <- c("prop","ORACLE", "CC", "MICE", "RF", "DAE")

# MNAR1
tab2MNAR1se = filter (getRows[,seCols], type=='MNAR1')
tab2MNAR1coverage = filter (getRows[,coverageCols], type=='MNAR1')
tab2MNAR1se$type = NULL
tab2MNAR1coverage$type = NULL

tab2MNAR1 <- cbind(t (tab1MNAR1bias), t (tab2MNAR1se), t (tab2MNAR1coverage))
tab2MNAR1 <- rbind(prop,tab2MNAR1)
rownames(tab2MNAR1) <- c("prop","ORACLE", "CC", "MICE", "RF", "DAE")

# MNAR2
tab2MNAR2se = filter (getRows[,seCols], type=='MNAR2')
tab2MNAR2coverage = filter (getRows[,coverageCols], type=='MNAR2')
tab2MNAR2se$type = NULL
tab2MNAR2coverage$type = NULL

tab2MNAR2 <- cbind(t (tab1MNAR2bias), t (tab2MNAR2se), t (tab2MNAR2coverage))
tab2MNAR2 <- rbind(prop,tab2MNAR2)
rownames(tab2MNAR2) <- c("prop","ORACLE", "CC", "MICE", "RF", "DAE")

# All mechs
tab2final <- rbind(tab2MCAR,tab2MAR,tab2MNAR1,tab2MNAR2)
print(tab2final)

tab2Treat <- round (tab2final, 4)
tab2Treat = tab2Treat[-c (1, 7:8,13:14,19:20),]
```

\newpage

## Treat
```{r echo=FALSE}
lsep = c("\\addlinespace", "", "", "", "\\addlinespace", "", "", "", "\\addlinespace", "", "", "", "", "\\addlinespace", "", "", "", "")

kable(tab2Treat, row.names=TRUE, align=c("l", "c", "c", "c", "c", "c", "c", "c", "c", "c"), format = "latex", booktabs = T, linesep = lsep, caption = "Treatment") %>%
  kable_styling(latex_options = c("striped", "hold_position"), full_width = F) %>%
  add_header_above(c(" "=1, "Low"=1, "Medium"=1, "High"=1, "Low"=1, "Medium"=1, "High"=1, "Low"=1, "Medium"=1, "High"=1)) %>%
  add_header_above(c(" "=1, "Bias"=3, "SE"=3, "Coverage"=3)) %>% 
  pack_rows("MCAR", 2, 5) %>% 
  pack_rows("MAR", 6, 9) %>% 
  pack_rows("MNAR 1", 10, 13) %>% 
  pack_rows("MNAR 2", 14, 17) 

#  group_rows(index=c(" "=1, "MCAR"=4, "MAR"=4, "MNAR 1"=4, "MNAR 2"=4))
```

\newpage

```{r echo=F, include=F}
# Table 3: ECOG Bias and MSE
getRows = allData[EcogInds,]

# MCAR
tab3MCARbias = filter (getRows[,biasCols], type=='MCAR')
tab3MCARbias$type = NULL

# MAR
tab3MARbias = filter (getRows[,biasCols], type=='MAR')
tab3MARbias$type = NULL

# MNAR1
tab3MNAR1bias = filter (getRows[,biasCols], type=='MNAR1')
tab3MNAR1bias$type = NULL

# MNAR2
tab3MNAR2bias = filter (getRows[,biasCols], type=='MNAR2')
tab3MNAR2bias$type = NULL

# Table 4: ECOG SE and coverage

# MCAR
tab4MCARse = filter (getRows[,seCols], type=='MCAR')
tab4MCARcoverage = filter (getRows[,coverageCols], type=='MCAR')
tab4MCARse$type = NULL
tab4MCARcoverage$type = NULL

tab4MCAR <- cbind(t (tab3MCARbias), t (tab4MCARse), t (tab4MCARcoverage))
tab4MCAR <- rbind(prop,tab4MCAR)
rownames(tab4MCAR) <- c("prop","ORACLE", "CC", "MICE", "RF", "DAE")

# MAR
tab4MARse = filter (getRows[,seCols], type=='MAR')
tab4MARcoverage = filter (getRows[,coverageCols], type=='MAR')
tab4MARse$type = NULL
tab4MARcoverage$type = NULL

tab4MAR <- cbind(t (tab3MARbias), t (tab4MARse), t (tab4MARcoverage))
tab4MAR <- rbind(prop,tab4MAR)
rownames(tab4MAR) <- c("prop","ORACLE", "CC", "MICE", "RF", "DAE")

# MNAR1
tab4MNAR1se = filter (getRows[,seCols], type=='MNAR1')
tab4MNAR1coverage = filter (getRows[,coverageCols], type=='MNAR1')
tab4MNAR1se$type = NULL
tab4MNAR1coverage$type = NULL

tab4MNAR1 <- cbind(t (tab3MNAR1bias), t (tab4MNAR1se), t (tab4MNAR1coverage))
tab4MNAR1 <- rbind(prop,tab4MNAR1)
rownames(tab4MNAR1) <- c("prop","ORACLE", "CC", "MICE", "RF", "DAE")

# MNAR2
tab4MNAR2se = filter (getRows[,seCols], type=='MNAR2')
tab4MNAR2coverage = filter (getRows[,coverageCols], type=='MNAR2')
tab4MNAR2se$type = NULL
tab4MNAR2coverage$type = NULL

tab4MNAR2 <- cbind(t (tab3MNAR2bias), t (tab4MNAR2se), t (tab4MNAR2coverage))
tab4MNAR2 <- rbind(prop,tab4MNAR2)
rownames(tab4MNAR2) <- c("prop","ORACLE", "CC", "MICE", "RF", "DAE")

# All mechs
tab4final <- rbind(tab4MCAR,tab4MAR,tab4MNAR1,tab4MNAR2)
print(tab4final)

tab4ECOG <- round (tab4final, 4)
tab4ECOG = tab4ECOG[-c (1, 7:8,13:14,19:20),]
```

\newpage

## ECOG
```{r echo=FALSE}
lsep = c("\\addlinespace", "", "", "", "\\addlinespace", "", "", "", "\\addlinespace", "", "", "", "", "\\addlinespace", "", "", "", "")

kable(tab4ECOG, row.names=TRUE, align=c("l", "c", "c", "c", "c", "c", "c", "c", "c", "c"), format = "latex", booktabs = T, linesep = lsep, caption = "ECOG") %>%
  kable_styling(latex_options = c("striped", "hold_position"), full_width = F) %>%
  add_header_above(c(" "=1, "Low"=1, "Medium"=1, "High"=1, "Low"=1, "Medium"=1, "High"=1, "Low"=1, "Medium"=1, "High"=1)) %>%
  add_header_above(c(" "=1, "Bias"=3, "SE"=3, "Coverage"=3)) %>% 
  pack_rows("MCAR", 2, 5) %>% 
  pack_rows("MAR", 6, 9) %>% 
  pack_rows("MNAR 1", 10, 13) %>% 
  pack_rows("MNAR 2", 14, 17) 

#  group_rows(index=c(" "=1, "MCAR"=4, "MAR"=4, "MNAR 1"=4, "MNAR 2"=4))
```



